services:
  nginx-git:

    build: .

    container_name: nginx-git-container

    ports:
      - "80:${NGINX_PORT}"

    volumes:
      - ${NGINX_LOG_DIR}:/var/log/nginx/
      - ${NGINX_PASS_DIR}:/etc/nginx/passwd/
      - ${GIT_REPOS_DIR}:/var/www/git/
    environment:
    
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
      - TZ=Europe/Moscow

    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s